### ISSUE TITLE
Adaptive-ness of Logo - mobile

### ISSUE THREAD

**Issue by kavinaya-lab** [paunn-gold/coming-soon-page#3]
![53D05F4C-AEFE-4F2B-90B8-3B99FD69719F](https://user-images.githubusercontent.com/68273144/90422109-a8473800-e0ba-11ea-8864-4408a2c9ad01.jpeg)

The logo is this big in the current version of mobile site.
I request it to be resized to this as the image below 
![774B4ABE-2261-4D5E-864B-9C48B5ED5907](https://user-images.githubusercontent.com/68273144/90422166-c44ad980-e0ba-11ea-8e40-f9a4ad6d20d5.png)

The position does not change. Just the sizing.

**Comment by revanth-s** [comment]
Fixed with commit 0986ce994f43c4cb5748d28b9d256d3a11776c1a
