### ISSUE TITLE
Adaptive-ness of Logo - desktop

### ISSUE THREAD

**Issue by kavinaya-lab** [paunn-gold/coming-soon-page#4]
I would like the logo and all the text to be sized down on the desktop browser.

Logo resize reference below 
![17636147-C7AB-409C-8623-886E87BD46C7](https://user-images.githubusercontent.com/68273144/90422916-d8dba180-e0bb-11ea-8d5c-0a252a8d2c37.jpeg)
The remaining text sizes can be halved for this version

**Comment by revanth-s** [comment]
Fixed with commit 0986ce994f43c4cb5748d28b9d256d3a11776c1a
