### ISSUE TITLE
Frame behaving independent

### ISSUE THREAD

**Issue by kavinaya-lab** [paunn-gold/coming-soon-page#5]
The logo and the frame behind Au are behaving independent of each other moving away and sometimes overlapping with “coming soon” 
![AFC892C5-447C-44C9-9D94-444A57128507](https://user-images.githubusercontent.com/68273144/90423223-5e5f5180-e0bc-11ea-9927-19f2662582b0.jpeg)

**Comment by revanth-s** [comment]
Fixed with commit 0986ce994f43c4cb5748d28b9d256d3a11776c1a
